version: '3.8'
services:
  app:
    build: .
    image: url-app
    container_name: url-app
    environment:
      - NODE_ENV=docker
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BASE_URL=http://localhost:5001
    ports:
      - 5000:5000
    depends_on:
      - redis
  redis:
    image: redis:7.2.5-alpine
    container_name: url-cache
    ports:
      - 6379:6379